FROM iojs:4.2.1
MAINTAINER Jonathan Ong "me@jongleberry.com"

RUN curl http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz | \
	tar -C /usr/local/bin/ -xJ --strip-components=1
